import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";

import { headers } from "next/headers";
import ContextProvider from "@/lib/context";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	const cookies = (await headers()).get("cookie");

	return (
		<html lang="en" className={`${GeistSans.variable}`}>
			<ContextProvider cookies={cookies}>
				<body>{children}</body>
			</ContextProvider>
		</html>
	);
}
